# Generated by Django 6.0.6 on 2026-07-06 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realisation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='realisations/'),
        ),
        migrations.CreateModel(
            name='EvenementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='evenements/')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gestion.evenement')),
            ],
            options={
                'verbose_name': 'Image événement',
                'ordering': ['ordre'],
            },
        ),
    ]
