# Generated by Django 6.0.6 on 2026-07-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_realisation_image_evenementimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
