# Generated by Django 6.0.6 on 2026-07-06 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_evenement_latitude_evenement_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='evenement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions', to='gestion.evenement'),
        ),
    ]
