# Generated by Django 6.0.6 on 2026-07-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_distribution_evenement'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
